//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Mobile.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherApp.Mobile.Resources.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Cities....
        /// </summary>
        public static string API_LOADING_CITIES_MESSAGE {
            get {
                return ResourceManager.GetString("API_LOADING_CITIES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting weather data for.
        /// </summary>
        public static string API_WEATHER_LOADING_MESSAGE {
            get {
                return ResourceManager.GetString("API_WEATHER_LOADING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language:.
        /// </summary>
        public static string CHOOSE_LANGUAGE {
            get {
                return ResourceManager.GetString("CHOOSE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string cloudy {
            get {
                return ResourceManager.GetString("cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        public static string drizzle {
            get {
                return ResourceManager.GetString("drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string fog {
            get {
                return ResourceManager.GetString("fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temp.
        /// </summary>
        public static string MAX_TEMP {
            get {
                return ResourceManager.GetString("MAX_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temp.
        /// </summary>
        public static string MIN_TEMP {
            get {
                return ResourceManager.GetString("MIN_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northeast.
        /// </summary>
        public static string northeast {
            get {
                return ResourceManager.GetString("northeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest.
        /// </summary>
        public static string northwest {
            get {
                return ResourceManager.GetString("northwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Outlook {
            get {
                return ResourceManager.GetString("Outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        public static string overcast {
            get {
                return ResourceManager.GetString("overcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string rain {
            get {
                return ResourceManager.GetString("rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a city....
        /// </summary>
        public static string SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string snow {
            get {
                return ResourceManager.GetString("snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string south {
            get {
                return ResourceManager.GetString("south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeast.
        /// </summary>
        public static string southeast {
            get {
                return ResourceManager.GetString("southeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southwest.
        /// </summary>
        public static string southwest {
            get {
                return ResourceManager.GetString("southwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny.
        /// </summary>
        public static string sunny {
            get {
                return ResourceManager.GetString("sunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string wind {
            get {
                return ResourceManager.GetString("wind", resourceCulture);
            }
        }
    }
}
